from src.visualization import run_app


if __name__ == "__main__":
    print("=" * 62)
    print("  Task 11 - Double Pendulum and Chaotic Motion")
    print("=" * 62)
    print()
    print("Dvojite kyvadlo:")
    print("  m1, m2  - hmotnosti zavazi")
    print("  l1, l2  - dlzky vlakien")
    print("  th1, th2 - uhly od vertikaly")
    print()
    print("Pohybove rovnice (Euler-Lagrange):")
    print("  Nelinearne ODR 2. radu pre th1'' a th2''.")
    print("  Numericka integracia: scipy.integrate.odeint (LSODA).")
    print()
    print("Mody:")
    print("  1. Standardne kyvadlo - jedno + stopa zavazia 2")
    print("  2. Chaos (3 kyvadla)  - mala zmena th1 (0.001 rad)")
    print("                          vyvolava velku divergenciu")
    print("  3. Bez stopy          - jedno kyvadlo, ciste rameno")
    print()
    print("Pociatocne podmienky (z PDF):")
    print("  th1 = 2*pi/6,  th2 = 5*pi/8,  th1' = th2' = 0")
    print()
    print("Animacia: real-time prehravanie pre-kalkulovanej trajektorie.")
    print()
    print("Spustam interaktivnu vizualizaciu...")
    print()
    run_app()
