from src.visualization import run_app


if __name__ == "__main__":
    print("=" * 58)
    print("  Task 5 – Pole-balancing: Q-learning → Neural Network")
    print("=" * 58)
    print()
    print("Q-learning parametre:")
    print("  alpha (learning rate) : 0.1")
    print("  gamma (discount)      : 0.99")
    print("  epsilon start         : 1.0  -> klesa na 0.01")
    print("  epsilon decay         : 0.995")
    print("  epizody               : 5 000")
    print()
    print("Diskretizacia stavu CartPole:")
    print("  cart_pos   : 6  intervalov  [-2.4,  2.4]")
    print("  cart_vel   : 6  intervalov  [-3.5,  3.5]")
    print("  pole_angle : 10 intervalov  [-0.26, 0.26]")
    print("  pole_vel   : 10 intervalov  [-3.5,  3.5]")
    print()
    print("Neuronova siet (supervised):")
    print("  architektura : 4 -> 64 -> 32 -> 2")
    print("  aktivacia    : ReLU + Softmax")
    print("  epochy       : 300")
    print("  batch size   : 64")
    print()
    print("Spustam interaktivnu vizualizaciu...")
    print()
    run_app()
